### ISSUE TITLE
ifpdf.sty doesn't work with amstex

### ISSUE THREAD

**Issue by paulvojta** [ho-tex/oberdiek#23] opened 2017-03-15 01:54 UTC
I get an error "! Missing \endcsname inserted." when running under amstex.  For example:
```
\input amstex
\input ifpdf.sty
Foo bar.
\bye
```
(And, no, I can't put \input ifpdf.sty first if I use amstex.fmt, which I usually do.)

Paul Vojta

**Comment by davidcarlisle** [comment] 2017-03-15 09:24
So it does,

You can add \string to make @ safe, so line 16 looks like

\csname ver\string @ifpdf.sty\endcsname{#3}}


I'll fix in the upcoming release, thanks.

David

**Comment by davidcarlisle** [comment] 2017-03-15 09:35
fixed via [master 8a83e82]

**Comment by davidcarlisle** [comment] 2017-03-15 15:35
While probably I should leave in the `\string @` as I think it worked that way before,  isn't it the case that before loading almost any plain or latex code into amstex you need to set the catcode of `@` to 11 and set it back to active later?

**Comment by paulvojta** [comment] 2017-03-15 20:31
On Wed, Mar 15, 2017 at 08:35:17AM -0700, David Carlisle wrote:
> While probably I should leave in the `\string @` as I think it worked that way before,  isn't it the case that before loading almost any plain or latex code into amstex you need to set the catcode of `@` to 11 and set it back to active later?

I don't see that documented anywhere.  Also, I regularly do \input supp-pdf and \input epsf without any catcode changes.

Thanks for the quick response.

Paul Vojta

**Comment by davidcarlisle** [comment] 2017-03-15 20:57
On 15 March 2017 at 20:31, Paul Vojta <notifications@github.com> wrote:

> On Wed, Mar 15, 2017 at 08:35:17AM -0700, David Carlisle wrote:
> > While probably I should leave in the `\string @` as I think it worked
> that way before, isn't it the case that before loading almost any plain or
> latex code into amstex you need to set the catcode of `@` to 11 and set it
> back to active later?
>
> I don't see that documented anywhere



Essentially no one, not even the AMS, uses amstex. There is no harm in
using amstex if that's what
you have always done, but it is now completely unsupported, so you are not
likely to find much
documentation on using latex or even plain code in that format.

But it is surely well documented that latex package code (and plain tex
internals)  use @ as a letter
so typically you have to set @ to letter before loading them from outside
latex
ifpdf was written not to assume it was letter so you could input it into
plain tex but it wasn't tested with
@ being catcode 13 and could fail even after the change here in other
formats, for example xmltex
format \ does not have catcode 0 so doesn't start tex commands.
It's simply not possible to support all formats that use unknown catcode
settings.

If you get away with loading latex or plain code without setting the
catcode of @
(especially in amstex where @ is catcode 13) then that is always going to
be by luck rather than design.

But anyway as adding a single \string here is easy enough
ifpdf will work by design with amstex next release:-)


> . Also, I regularly do \input supp-pdf and \input epsf without any catcode
> changes.
>

the first sets catcode to 11 and sets it back, the second doesn't use @
only a tiny fraction of available latex code does either of those things.


>
> Thanks for the quick response.
>
> Paul Vojta
>


David

**Comment by davidcarlisle** [comment] 2017-03-21 16:02
A version addressing this is now on ctan, thanks for the comment.

**Closed by davidcarlisle** 2017-03-21 16:02 UTC

**Comment by paulvojta** [comment] 2017-03-22 00:12
Thanks!

Paul Vojta
